PARCEL_FIELDS = [
    "ACCTID", "GEOGCODE", "ADDRESS", "STRTNUM", "STRTNAM", "OWNNAME1",
    "ZONING", "LU", "DESCLU", "ACRES", "LANDAREA", "YEARBLT",
    "SQFTSTRC", "NFMLNDVL", "NFMIMPVL", "NFMTTLVL", "DIGXCORD", "DIGYCORD", "geometry"
]

VALUE_COLUMNS = ["NFMLNDVL", "NFMIMPVL", "NFMTTLVL"]
PARCEL_SPECIFIC_COLUMNS = ["GEOGCODE", "OWNNAME1", "ZONING", "LU", "DESCLU", "ACRES", "LANDAREA", "YEARBLT", "SQFTSTRC"]
LOCATION_COLUMNS = ["ADDRESS", "STRTNUM", "STRTNAM"]
IDENTIFIER_COLUMN = ["ACCTID"]
ASEEMENT_CODE = ["GEOGCODE"]


BALTIMORE_CENTRAL = (-76.6122, 39.2904)  # (lon, lat)
